
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


apiVersion: portal.apiconnect.ibm.com/v1beta1
kind: PortalCluster
metadata:
  name: portal-red-interna
  labels: {
    app.kubernetes.io/instance: "portal",
    app.kubernetes.io/managed-by: "ibm-apiconnect",
    app.kubernetes.io/name: "portal"
  }
spec:
  siteName: dc1
  encryptionSecret:
    secretName: ptl-red-interna-encryption-key  
  multiSiteHA:
    mode: active
    replicationEndpoint:
      annotations:
        certmanager.k8s.io/issuer: ingress-issuer 
      hosts:
      - name: s01plxwk8s045.sunat.peru  #worker ingress 172.17.4.159 RED Interna SC
        secretName: ptl-red-interna-replication
    replicationPeerFQDN: s00plxwk8s045.sunat.peru  #worker ingress 172.17.0.159 RED Interna SI
    tlsClient:
      secretName: ptl-red-interna-replication-client
  version: 10.0.2.0
  profile: n3xc4.m8
  imagePullSecrets:
    - apic-registry-secret
  imageRegistry: 192.168.86.100:30000
  portalAdminEndpoint:
    annotations:
      certmanager.k8s.io/issuer: ingress-issuer
    hosts:
    - name: api-portal-management-intranet.sunat.peru
      secretName: portal-admin
  portalUIEndpoint:
    annotations:
      certmanager.k8s.io/issuer: ingress-issuer
    hosts:
    - name: api-portal-intranet.sunat.peru
      secretName: portal-web
  databaseVolumeClaimTemplate:
    storageClassName: rook-ceph-block
    volumeSize: 60Gi
  databaseLogsVolumeClaimTemplate:
    storageClassName: rook-ceph-block
    volumeSize: 12Gi
  webVolumeClaimTemplate:
    storageClassName: rook-ceph-block
    volumeSize: 30Gi
  backupVolumeClaimTemplate:
    storageClassName: rook-ceph-block
    volumeSize: 60Gi
  adminVolumeClaimTemplate:
    storageClassName: rook-ceph-block
    volumeSize: 20Gi
  adminClientSubjectDN: CN=portal-admin-client,O=cert-manager
  microServiceSecurity: certManager
  certManagerIssuer:
    name: selfsigning-issuer
    kind: Issuer
  license:
    accept: true
    use: production
    license: 'L-RJON-BZ5LJ5'
  nodeSelector:
    nodegroup-type: apic-red-interna
